apiVersion: v1
kind: Pod
metadata:
  name: calculator-app
  labels:
    app.kubernetes.io/name: calculator
spec:
  containers:
  - name: calculator-app
    image: heiderhengstmann/javaapps:calculator-v1.1
    ports:
    - containerPort: 9376

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: calculator
  ports:
  - name: calculator-service-port
    protocol: TCP
    ports: 
    - protocol: TCP
      port: 9376
      targetPort: 9376
